// <auto-generated />
namespace Leder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddStringArray : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStringArray));
        
        string IMigrationMetadata.Id
        {
            get { return "201911280342570_AddStringArray"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
